//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyrianPound.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyrianPound.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ -&gt; SYP.
        /// </summary>
        internal static string BtnDollarToSyrianPound {
            get {
                return ResourceManager.GetString("BtnDollarToSyrianPound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to € -&gt; SYP.
        /// </summary>
        internal static string BtnEuroToSyrianPound {
            get {
                return ResourceManager.GetString("BtnEuroToSyrianPound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYP -&gt; $.
        /// </summary>
        internal static string BtnSyrianPoundToDollar {
            get {
                return ResourceManager.GetString("BtnSyrianPoundToDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYP -&gt; €.
        /// </summary>
        internal static string BtnSyrianPoundToEuro {
            get {
                return ResourceManager.GetString("BtnSyrianPoundToEuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        internal static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying.
        /// </summary>
        internal static string LblBuying {
            get {
                return ResourceManager.GetString("LblBuying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.S Dollar.
        /// </summary>
        internal static string LblDollar {
            get {
                return ResourceManager.GetString("LblDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro.
        /// </summary>
        internal static string LblEuro {
            get {
                return ResourceManager.GetString("LblEuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling.
        /// </summary>
        internal static string LblSelling {
            get {
                return ResourceManager.GetString("LblSelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYP.
        /// </summary>
        internal static string SyrianPoundSymbol {
            get {
                return ResourceManager.GetString("SyrianPoundSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        internal static string TabNameCalculator {
            get {
                return ResourceManager.GetString("TabNameCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates.
        /// </summary>
        internal static string TabNameRates {
            get {
                return ResourceManager.GetString("TabNameRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syrain Pound Exchange Rate.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
